GuzabaPlatform\Platform\Application\RedisConnection:
  host: 127.0.0.1
  port: 6379
  timeout: 1.5
  password: ''
  database: 0
  services: [ConnectionFactory]
  expiry_time: 3600
GuzabaPlatform\Platform\Application\MysqlConnection:
  host: 127.0.0.2
  port: 3306
  user: user
  password: pass
  database: db
  tprefix: db_